spring:
  datasource:
    url: jdbc:h2:mem:nftshop
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop # База данных создается при запуске и удаляется при завершении
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Liquibase configuration
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml